# Generated by Django 5.2.4 on 2025-07-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
